#!/bin/bash
set -e

echo "Installing pybind11 version ${PYBIND11_VERSION}..."
TMP_DIR="$(mktemp -d)"
git clone https://github.com/pybind/pybind11.git "${TMP_DIR}"
cd "${TMP_DIR}"
git checkout "v${PYBIND11_VERSION}"
mkdir build
cd build
cmake -DPYBIND11_TEST=OFF ..
make -j "$(nproc)"
make install
cd /
rm -rf "${TMP_DIR}"
echo "pybind11 installed successfully"
